/**
 * @file error.ts
 * @namespace AOXCDAO.Core.Security
 * @version 2.0.0
 * @description Global Error Signatures & Forensic Codes - (Master-Numerical-Locked)
 * Defines universal error codes for automated mitigation across all Vessels.
 */

/**
 * @constant SECURITY_ERRORS
 * @description 0xFBXX Series: High-priority security and logic violations.
 * Triggers the Quasar Sentry isolation protocols.
 */
export const SECURITY_ERRORS = {
    ERR_SIG_BREACH:    0xfb01, // Unauthorized vessel bridge access
    ERR_SIG_INJECTION: 0xfb02, // Malicious code or state injection attempt
    ERR_SIG_OVERRIDE:  0xfb03, // Illegal system override
} as const;

/**
 * @constant ECONOMIC_ERRORS
 * @description 0xECXX Series: Economic anomalies and liquidity protection.
 */
export const ECONOMIC_ERRORS = {
    ERR_SIG_DRAIN:       0xec01, // Rapid or abnormal fund withdrawal
    ERR_SIG_ORACLE_FAIL: 0xec02, // External price/data feed corruption
    ERR_SIG_DOUBLE_SPEND:0xec03, // Transaction integrity failure
} as const;

/**
 * @constant GOVERNANCE_ERRORS
 * @description 0x4756XX Series: Integrity violations in voting and merit systems.
 */
export const GOVERNANCE_ERRORS = {
    ERR_SIG_VOTE_MANIP: 0x475601, // Fraudulent voting activity
    ERR_SIG_RANK_FRAUD: 0x475602, // Credential falsification
} as const;

// -----------------------------------------------------------------------------
// ACADEMIC TYPE DEFINITIONS (v2.0.0 UPDATED)
// -----------------------------------------------------------------------------

export type SecurityError = (typeof SECURITY_ERRORS)[keyof typeof SECURITY_ERRORS];
export type EconomicError = (typeof ECONOMIC_ERRORS)[keyof typeof ECONOMIC_ERRORS];
export type GovernanceError = (typeof GOVERNANCE_ERRORS)[keyof typeof GOVERNANCE_ERRORS];

export type GlobalErrorSignature = SecurityError | EconomicError | GovernanceError;

/**
 * @interface IForensicIncident
 * @description Standardized structure for an error report generated by Sentinels.
 */
export interface IForensicIncident {
    readonly signature: GlobalErrorSignature;
    readonly origin_vessel: number; 
    readonly severity: number; // 0.0 to 1.0 (Criticality)
    readonly actor_hash: string; 
    readonly forensic_payload: string; 
    readonly timestamp: number; 
}

/**
 * @class ForensicAnalyst
 * @description Active logic for error classification and automated threat mitigation.
 */
export class ForensicAnalyst {
    /**
     * @method calculateSeverity
     * @description Assigns a severity weight based on the error category.
     */
    public static calculateSeverity(signature: GlobalErrorSignature): number {
        const hex = signature.toString(16);
        
        if (hex.startsWith('fb')) return 1.0; // Security = Maximum Severity
        if (hex.startsWith('ec')) return 0.8; // Economic = High Severity
        if (hex.startsWith('4756')) return 0.6; // Governance = Moderate Severity
        
        return 0.1;
    }

    /**
     * @method getMitigationAction
     * @description Returns the required protocol response for a specific error.
     */
    public static getMitigationAction(signature: GlobalErrorSignature): string {
        const severity = this.calculateSeverity(signature);

        if (severity >= 1.0) return "QUASAR_LOCKDOWN";
        if (severity >= 0.8) return "TREASURY_FREEZE";
        if (severity >= 0.6) return "MERIT_PENALTY";
        
        return "LOG_ONLY";
    }

    /**
     * @method createIncidentReport
     * @description Generates a formal forensic manifest for the Chief.
     */
    public static createIncidentReport(
        signature: GlobalErrorSignature, 
        vesselId: number, 
        actor: string,
        data: string
    ): IForensicIncident {
        return {
            signature,
            origin_vessel: vesselId,
            severity: this.calculateSeverity(signature),
            actor_hash: actor,
            forensic_payload: data,
            timestamp: Date.now()
        };
    }
}

/**
 * @description Verification flag for system-wide integrity checks.
 */
export const FORENSIC_ERROR_LOADED: boolean = true;
