/**
 * @file err00_AoxcGenesisMaster_180226.ts
 * @namespace AOXCDAO.Core.Errors
 * @version 2.0.0 AOXCDAO V2 AKDENIZ
 * @status IMMUTABLE_ERROR_ROOT
 * @description Standardized Error Registry for 1024 Shards & 1B+ Users.
 */

export enum GENESIS_ERROR_CODES {
    // 0x100s: AUTH & IDENTITY
    ERR_AUTH_LEVEL_INSUFFICIENT = 0x101,
    ERR_PASSPORT_EXPIRED        = 0x102,
    ERR_INVALID_QUANTUM_SIG     = 0x103,
    ERR_ROLE_MISMATCH           = 0x104,

    // 0x200s: BANK & RESOURCES
    ERR_INSUFFICIENT_ENERGY     = 0x201,
    ERR_INSUFFICIENT_MERIT      = 0x202,
    ERR_LIQUIDITY_LOCK_ACTIVE   = 0x203,
    ERR_RESOURCE_OVERFLOW       = 0x204,

    // 0x300s: NETWORK & SHARDS
    ERR_SHARD_CAPACITY_FULL     = 0x301,
    ERR_SHARD_ISOLATION_ACTIVE  = 0x302,
    ERR_VESSEL_SYNC_FAILED      = 0x303,
    ERR_BRIDGE_COHERENCE_LOST   = 0x304,

    // 0x400s: GOVERNANCE
    ERR_QUORUM_NOT_MET          = 0x401,
    ERR_VETO_POWER_TRIGGERED    = 0x402,
    ERR_PROPOSAL_TYPE_INVALID   = 0x403
}

export const ERROR_GENESIS_LOADED: boolean = true;
